//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestL2_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OD
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int OrderHistory { get; set; }
    
        public virtual OH OH { get; set; }
        public virtual Product Product { get; set; }
    }
}
