//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestL2_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OH
    {
        public OH()
        {
            this.ODs = new HashSet<OD>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime OD { get; set; }
        public int Total { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OD> ODs { get; set; }
    }
}
